name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
          GOOS=windows go build -o ./bin/win_network_gopher.exe ./main.go
          GOOS=linux go build -o ./bin/lin_network_gopher ./main.go
          GOOS=darwin go build -o ./bin/mac_network_gopher ./main.go

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: true
            title: "Development Build"
            files: |
              ./bin/win_network_gopher.exe
              ./bin/lin_network_gopher
              ./bin/mac_network_gopher
